import './_styles/style.css'

export const metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Codevolution"
  },
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header> Header </header>
        {children}
        <footer> Footer </footer>
      </body>
    </html>
  )
}
